// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
//J-
package de.esoco.ewt.impl.gwt;
import com.google.gwt.resources.client.CssResource;
public interface GewtCss extends CssResource {
  
  @ClassName("ewt-TableRow")
  String ewtTableRow();
  
  @ClassName("ewt-Odd")
  String ewtOdd();
  
  @ClassName("ewt-Main")
  String ewtMain();
  
  @ClassName("ewt-Empty")
  String ewtEmpty();
  
  @ClassName("ewt-Error")
  String ewtError();
  
  @ClassName("ewt-Limited")
  String ewtLimited();
  
  @ClassName("ewt-Selected")
  String ewtSelected();
  
  @ClassName("ewt-Calculator")
  String ewtCalculator();

  @ClassName("ewt-Chart")
  String ewtChart();
  
  @ClassName("ewt-DataTable")
  String ewtDataTable();
  
  @ClassName("ewt-EdgeLayout")
  String ewtEdgeLayout();
  
  @ClassName("ewt-Filter")
  String ewtFilter();
  
  @ClassName("ewt-Header")
  String ewtHeader();
  
  @ClassName("ewt-Icon")
  String ewtIcon();
  
  @ClassName("ewt-ImageLabel")
  String ewtImageLabel();
  
  @ClassName("ewt-MainView")
  String ewtMainView();

  @ClassName("ewt-ChildView")
  String ewtChildView();

  @ClassName("ewt-DialogView")
  String ewtDialogView();
  
  @ClassName("ewt-DialogTitle")
  String ewtDialogTitle();
  
  @ClassName("ewt-MessageBox")
  String ewtMessageBox();
  
  @ClassName("ewt-MessageIcon")
  String ewtMessageIcon();
  
  @ClassName("ewt-MessageLabel")
  String ewtMessageLabel();
  
  @ClassName("ewt-NavButtons")
  String ewtNavButtons();
  
  @ClassName("ewt-NoChartDataLabel")
  String ewtNoChartDataLabel();
  
  @ClassName("ewt-NoSelect")
  String ewtNoSelect();
  
  @ClassName("ewt-Resizer")
  String ewtResizer();
  
  @ClassName("ewt-SortIndicator")
  String ewtSortIndicator();
  
  @ClassName("ewt-Spinner")
  String ewtSpinner();
  
  @ClassName("ewt-SpinnerButton")
  String ewtSpinnerButton();
  
  @ClassName("ewt-SpinnerButton-down")
  String ewtSpinnerButtonDown();
  
  @ClassName("ewt-SpinnerButton-down-disabled")
  String ewtSpinnerButtonDownDisabled();
  
  @ClassName("ewt-SpinnerButton-down-hovering")
  String ewtSpinnerButtonDownHovering();
  
  @ClassName("ewt-SpinnerButton-up")
  String ewtSpinnerButtonUp();
  
  @ClassName("ewt-SpinnerButton-up-disabled")
  String ewtSpinnerButtonUpDisabled();
  
  @ClassName("ewt-SpinnerButton-up-hovering")
  String ewtSpinnerButtonUpHovering();
  
  @ClassName("ewt-SpinnerButtons")
  String ewtSpinnerButtons();
  
  @ClassName("ewt-SpinnerInput")
  String ewtSpinnerInput();
  
  @ClassName("ewt-Table")
  String ewtTable();
  
  @ClassName("ewt-Table-disabled")
  String ewtTableDisabled();
  
  @ClassName("ewt-TableFilterButton")
  String ewtTableFilterButton();
  
  @ClassName("ewt-TableFilterButton-active")
  String ewtTableFilterButtonActive();
  
  @ClassName("ewt-TableFilterPopup")
  String ewtTableFilterPopup();
  
  @ClassName("ewt-TableFilterValue")
  String ewtTableFilterValue();
  
  @ClassName("ewt-TableFilterValue-disabled")
  String ewtTableFilterValueDisabled();
  
  @ClassName("ewt-TagDisplay")
  String ewtTagDisplay();
  
  @ClassName("ewt-TagDisplay-selected")
  String ewtTagDisplaySelected();
  
  @ClassName("ewt-TagField")
  String ewtTagField();
  
  @ClassName("ewt-TagField-disabled")
  String ewtTagFieldDisabled();
  
  @ClassName("ewt-TagInput")
  String ewtTagInput();
  
  @ClassName("ewt-TimePicker")
  String ewtTimePicker();
  
  @ClassName("ewt-Toolbar")
  String ewtToolbar();
  
  @ClassName("ewt-Tooltip")
  String ewtTooltip();
  
  @ClassName("ewt-TreeNode")
  String ewtTreeNode();

  @ClassName("ewt-ContentPanel")
  String ewtContentPanel();

  @ClassName("ewt-FlexLayout")
  String ewtFlexLayout();
  
  @ClassName("ewt-GridLayout")
  String ewtGridLayout();

  // GWT DatePicker styles for reference from extended classes
  String datePickerMonth();
  String datePickerMonthSelector();
}


